sudo: true
language: node_js
node_js:
  - "0.11"
  - "0.10"
  - "0.12"
  - iojs
os:
  - osx
before_install:
  - npm update -g npm
  - npm install -g bob coveralls --loglevel error
  - brew update
  - brew install libusb
script:
  - bob build
  - cat .bob/coverage/buster-istanbul/lcov.info | coveralls
