sudo: true
language: node_js
node_js:
  - "0.11"
  - "0.10"
  - "0.12"
  - iojs
before_install:
  - npm update -g npm
  - npm install -g bob coveralls --loglevel error
  - sudo apt-get update
  - sudo apt-get install libudev-dev libusb-1.0-0-dev
script:
  - bob build
  - cat .bob/coverage/buster-istanbul/lcov.info | coveralls
