sudo: true
env:
  - NODE_VERSION="0.10"
  - NODE_VERSION="0.11"
  - NODE_VERSION="0.12"
  - NODE_VERSION="iojs"
os:
  - osx
before_install:
  - npm update -g npm
  - npm install -g bob coveralls --loglevel error
  - brew update
  - brew install libusb
  - brew install nvm
  - nvm install $NODE_VERSION
  - node --version
  - npm install
script:
  - bob build
  - cat .bob/coverage/buster-istanbul/lcov.info | coveralls
